services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: cfdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      # - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./script/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
      - ./script:/script
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d cfdb" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

# volumes:
#   pgdata:
#     driver: local
